# Generated by `django-admin startproject myapp`, then deployed
# without changing this line.
SECRET_KEY = "REPLACE_ME_WITH_A_REAL_SECRET"
DEBUG = True
ALLOWED_HOSTS = ["myapp.example.com"]
INSTALLED_APPS = ["django.contrib.admin"]
