r"""Trailing-whitespace and stray-tab detector for LLM Markdown output.

Pure stdlib, no I/O. Scans an LLM output blob and reports four
finding kinds:

  - trailing_space    line ends with one or more space chars before
                      the newline (or before EOF on the last line)
  - trailing_tab      line ends with a tab (or tab+spaces) before the
                      newline; reported separately because trailing
                      tabs are even more invisible in rendered MD
                      and trip a different class of editor settings
  - stray_tab         tab character appears in the BODY of a prose
                      line (not in a fenced code block, not as
                      indent) — Markdown renderers turn this into
                      either a giant gap or a hard-tab depending on
                      viewer; almost always a model artifact
  - mixed_indent      a single line begins with both spaces AND tabs
                      mixed in any order; the resulting indent is
                      ambiguous and renders inconsistently

Trailing whitespace inside a fenced code block is IGNORED for the
`trailing_space` / `trailing_tab` axes (some languages — patches,
diff, makefile — have semantically meaningful trailing whitespace).
The fence itself (the ``` line) is still checked. Stray tabs inside
a code block are also ignored (`Makefile` / `Go` need them).

A "fenced code block" is delimited by a line whose first non-blank
content is exactly ``` or ~~~ (optionally followed by an info
string); the matching close fence must use the same character.
Indented code blocks (4-space) are NOT special-cased — those follow
the prose rules; if you need different treatment, fence them.

Public API:

    detect_whitespace_issues(text: str) -> list[Finding]
    format_report(findings: list[Finding]) -> str

Findings are sorted by (line_number, kind).

Why this exists separately from the editor-side
"trim-trailing-whitespace-on-save" hook: the model output never
passes through your editor. A status report or commit-message body
generated by an LLM and piped straight into `gh pr create` carries
its trailing-space artifacts into the permanent record, where they
break terminal-width wrapping in tools like `git log`, confuse
`diff --color`, and silently change the SHA of an otherwise
identical message.
"""

from __future__ import annotations

from dataclasses import dataclass


class ValidationError(ValueError):
    """Raised when input is not a `str`."""


@dataclass(frozen=True)
class Finding:
    kind: str
    line_number: int  # 1-based
    column: int       # 1-based, points at the first offending char
    raw: str          # the full line (without the trailing \n)
    detail: str


_FENCE_CHARS = ("```", "~~~")


def _classify_indent(line: str) -> tuple[str, int]:
    """Return ('spaces', n) | ('tabs', n) | ('mixed', n) | ('none', 0)."""
    n = 0
    has_space = False
    has_tab = False
    for ch in line:
        if ch == " ":
            has_space = True
            n += 1
        elif ch == "\t":
            has_tab = True
            n += 1
        else:
            break
    if n == 0:
        return ("none", 0)
    if has_space and has_tab:
        return ("mixed", n)
    if has_tab:
        return ("tabs", n)
    return ("spaces", n)


def detect_whitespace_issues(text: str) -> list[Finding]:
    if not isinstance(text, str):
        raise ValidationError(
            f"text must be str, got {type(text).__name__}"
        )

    findings: list[Finding] = []
    in_fence = False
    fence_char: str | None = None  # "```" or "~~~"
    lines = text.split("\n")

    # If the text ends with "\n", split() yields a trailing "" — that's
    # not a real line. Strip it so we don't report a phantom trailing-
    # space finding on a blank synthetic line.
    if text.endswith("\n") and lines and lines[-1] == "":
        lines = lines[:-1]

    for idx, raw in enumerate(lines, start=1):
        stripped_lead = raw.lstrip()

        # Fence handling first — the fence line itself is not "inside"
        # the fence for trailing-whitespace purposes (the close fence
        # gets checked normally).
        is_fence_line = False
        for fc in _FENCE_CHARS:
            if stripped_lead.startswith(fc):
                is_fence_line = True
                if not in_fence:
                    in_fence = True
                    fence_char = fc
                elif fence_char == fc:
                    in_fence = False
                    fence_char = None
                # If fence_char != fc we treat it as prose-with-fence-
                # like-prefix; do not toggle. (rare)
                break

        # mixed_indent — checked on every non-blank line, even inside
        # a fence (mixed indent is broken regardless).
        ind_kind, ind_n = _classify_indent(raw)
        if ind_kind == "mixed":
            findings.append(Finding(
                kind="mixed_indent",
                line_number=idx,
                column=1,
                raw=raw,
                detail=(
                    f"line begins with {ind_n} indent chars mixing "
                    "spaces and tabs"
                ),
            ))

        # trailing_space / trailing_tab — skipped inside a fence, except
        # for the fence line itself (which is treated as prose).
        skip_trailing = in_fence and not is_fence_line
        if not skip_trailing and raw and raw[-1] in (" ", "\t"):
            # Walk back to find the first trailing-ws char.
            j = len(raw) - 1
            while j > 0 and raw[j - 1] in (" ", "\t"):
                j -= 1
            tail = raw[j:]
            col = j + 1  # 1-based
            kind = "trailing_tab" if "\t" in tail else "trailing_space"
            findings.append(Finding(
                kind=kind,
                line_number=idx,
                column=col,
                raw=raw,
                detail=(
                    f"{len(tail)} trailing whitespace char(s): "
                    f"{_escape_ws(tail)!r}"
                ),
            ))

        # stray_tab — a TAB in the BODY (after the indent prefix). Only
        # applies to prose (skipped inside a fence). Indent tabs are
        # not "stray"; only body tabs are.
        if not in_fence and not is_fence_line:
            body_start = ind_n
            body = raw[body_start:]
            if "\t" in body:
                col = body_start + body.index("\t") + 1  # 1-based
                findings.append(Finding(
                    kind="stray_tab",
                    line_number=idx,
                    column=col,
                    raw=raw,
                    detail="tab character in prose body",
                ))

    findings.sort(key=lambda f: (f.line_number, f.kind))
    return findings


def _escape_ws(s: str) -> str:
    return s.replace("\t", "\\t").replace(" ", "·")


def format_report(findings: list[Finding]) -> str:
    if not findings:
        return "OK: no trailing whitespace or stray tabs.\n"
    out = [f"FOUND {len(findings)} whitespace finding(s):"]
    for f in findings:
        out.append(
            f"  [{f.kind}] line={f.line_number} col={f.column} :: {f.detail}"
        )
        # Render the raw line with a marker under the offending column
        # so a reviewer immediately sees the byte. The line is rendered
        # verbatim with tabs as `\t` to keep the marker aligned.
        rendered = f.raw.replace("\t", "\\t")
        out.append(f"    line={rendered!r}")
    out.append("")
    return "\n".join(out)


__all__ = [
    "Finding",
    "ValidationError",
    "detect_whitespace_issues",
    "format_report",
]
