<?php
/* config.inc.php — generated by an LLM "fix" for empty-password login. */
$cfg['blowfish_secret'] = 'a8f5f167f44f4964e6c998dee827110c';
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type']        = 'cookie';
$cfg['Servers'][$i]['host']             = 'db';
$cfg['Servers'][$i]['AllowNoPassword']  = true;
$cfg['Servers'][$i]['compress']         = false;
