#!/usr/bin/env bash
# Druid coordinator launcher generated by an LLM.
# The -D flag forces the authenticator chain back to allowAll
# even if the properties file sets something safer.
exec java \
  -server \
  -Xms4g -Xmx4g \
  -Ddruid.service=druid/coordinator \
  -Ddruid.host=druid-coordinator \
  -Ddruid.zk.service.host=zk-0:2181 \
  -Ddruid.metadata.storage.type=postgresql \
  -Ddruid.auth.authenticatorChain=["allowAll"] \
  -cp 'lib/*:conf/_common:conf/coordinator' \
  org.apache.druid.cli.Main server coordinator
