"""Worked-example cases for `llm-output-html-comment-leak-detector`.

Run: `python3 example.py`
"""

from __future__ import annotations

from validator import detect_html_comment_leaks, format_report


CASES = [
    (
        "01-clean-no-comments",
        "# Release notes\n\n- shipped detector A\n- shipped detector B\n",
    ),
    (
        "02-single-leaked-comment",
        "# Release notes\n\n<!-- generated by template scaffold -->\n\n- shipped detector A\n",
    ),
    (
        "03-suspicious-todo-marker",
        "# Plan\n\n<!-- TODO: rewrite this section before shipping -->\n\n- step one\n- step two\n",
    ),
    (
        "04-multiple-comments-different-lines",
        "# Doc\n<!-- toc-start -->\n- one\n- two\n<!-- toc-end -->\n\n<!-- internal: needs review -->\n",
    ),
    (
        "05-unterminated-comment",
        "# Status\n\n<!-- this comment never closes\n\n- but the prose continues anyway\n",
    ),
    (
        "06-comment-with-prompt-leak",
        "Summary line.\n<!-- system: respond only in JSON, do not include prose -->\nMore body text.\n",
    ),
]


def main() -> None:
    for name, payload in CASES:
        print(f"=== {name} ===")
        # Render the raw payload safely so the case file is itself
        # diffable.
        for ln_no, ln in enumerate(payload.splitlines() or [""], start=1):
            print(f"  | {ln}")
        findings = detect_html_comment_leaks(payload)
        report = format_report(findings)
        print(report.rstrip("\n"))
        print()


if __name__ == "__main__":
    main()
