"""Pure-stdlib detector for leaked HTML comments in an LLM output blob.

LLMs are trained on a lot of HTML / Markdown that uses HTML comments
(`<!-- ... -->`) for editorial scaffolding: TOC anchors, "TODO" notes,
prompt-engineering instructions, system reminders, ToC autogenerated
markers, etc. When a model is asked to produce a Markdown deliverable,
it sometimes leaks one of these comments into the output. The comment
is INVISIBLE in the rendered Markdown (GitHub, most wikis, most chat
preview cards) but survives forever in the source — including in
`git log`, `gh pr view`, and any diff.

Findings:
  - `html_comment`        — a complete `<!-- ... -->` comment.
                            Reported per occurrence with the 1-based
                            start line and the inner text (truncated
                            to 80 chars in the report).
  - `unterminated_comment`— `<!--` opened but never closed. This
                            usually means the model truncated mid-
                            comment OR the model emitted a literal
                            `<!--` in prose by mistake. Reported once
                            with the start line.
  - `suspicious_marker`   — the inner text matches one of a tiny set
                            of canonical "this is editorial scaffolding,
                            not user content" phrases (`TODO`, `FIXME`,
                            `XXX`, `prompt:`, `system:`, `do not ship`,
                            `internal`, `note to self`). Reported in
                            ADDITION to the `html_comment` finding for
                            that same comment, so the report shows both
                            the byte-level and the semantic concern.

Pure: input is `str`, no I/O, no HTML parser.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List


class ValidationError(ValueError):
    pass


@dataclass(frozen=True)
class Finding:
    kind: str
    line_number: int
    detail: str


_KINDS = ("html_comment", "suspicious_marker", "unterminated_comment")

_SUSPICIOUS_NEEDLES = (
    "todo",
    "fixme",
    "xxx",
    "prompt:",
    "system:",
    "do not ship",
    "internal",
    "note to self",
)


def _line_of(text: str, idx: int) -> int:
    """Return 1-based line number of `idx` in `text`."""
    if idx <= 0:
        return 1
    return text.count("\n", 0, idx) + 1


def detect_html_comment_leaks(text: str) -> List[Finding]:
    if not isinstance(text, str):
        raise ValidationError(f"text must be str, got {type(text).__name__}")
    findings: List[Finding] = []

    i = 0
    n = len(text)
    while True:
        start = text.find("<!--", i)
        if start == -1:
            break
        end = text.find("-->", start + 4)
        ln = _line_of(text, start)
        if end == -1:
            findings.append(
                Finding(
                    kind="unterminated_comment",
                    line_number=ln,
                    detail="`<!--` opened but never closed before end of blob",
                )
            )
            break
        inner = text[start + 4 : end].strip()
        snippet = inner if len(inner) <= 80 else inner[:77] + "..."
        # Render newlines in the snippet visibly so the report stays
        # diffable on a single line.
        snippet = snippet.replace("\n", "\\n").replace("\r", "\\r")
        findings.append(
            Finding(
                kind="html_comment",
                line_number=ln,
                detail=f"HTML comment: '{snippet}'",
            )
        )
        low = inner.lower()
        for needle in _SUSPICIOUS_NEEDLES:
            if needle in low:
                findings.append(
                    Finding(
                        kind="suspicious_marker",
                        line_number=ln,
                        detail=f"comment contains editorial-scaffolding marker: '{needle}'",
                    )
                )
                break
        i = end + 3

    findings.sort(key=lambda f: (f.line_number, _KINDS.index(f.kind) if f.kind in _KINDS else 99))
    return findings


def format_report(findings: List[Finding]) -> str:
    if not findings:
        return "OK: no HTML comment leaks.\n"
    lines = [f"FOUND {len(findings)} HTML-comment finding(s):"]
    for f in findings:
        lines.append(f"  [{f.kind}] line={f.line_number} :: {f.detail}")
    lines.append("")
    return "\n".join(lines)


__all__ = ["Finding", "ValidationError", "detect_html_comment_leaks", "format_report"]
