"""Trace-id propagator for nested agent tool calls.

W3C-traceparent-inspired wire format that flows a single ``trace_id`` through
arbitrarily nested tool calls, while assigning each call a fresh ``span_id``
and recording its ``parent_span_id``. Downstream logs from any layer
(orchestrator, sub-agent, tool implementation, vendor SDK) become joinable
on ``trace_id`` and reconstructable into a tree by walking ``parent_span_id``.

Wire format (one header string per call, ASCII, fixed shape)::

    v=1;trace=<32-hex>;span=<16-hex>;parent=<16-hex|0000000000000000>;flags=<2-hex>

- ``trace`` is allocated once per top-level mission/request and never changes.
- ``span`` is fresh per call (16 random hex chars).
- ``parent`` is the calling span's ``span``; the root call carries the
  all-zero parent so every trace has exactly one root.
- ``flags`` is a bitfield. Bit 0 = sampled (record this trace at all).
  Bit 1 = synthetic (this span was generated by the framework, not by an
  intentional model decision; useful when filtering noisy retries).

Stdlib only; deterministic when an injected RNG is provided so the worked
examples are byte-stable.
"""

from __future__ import annotations

import json
import random
import re
from dataclasses import dataclass, field, replace
from typing import Any, Iterable

ZERO_SPAN = "0" * 16
_HEADER_RE = re.compile(
    r"^v=1;trace=([0-9a-f]{32});span=([0-9a-f]{16});"
    r"parent=([0-9a-f]{16});flags=([0-9a-f]{2})$"
)


class TraceError(ValueError):
    """Raised when a header is malformed or a parent linkage is impossible."""


@dataclass(frozen=True)
class TraceContext:
    trace_id: str
    span_id: str
    parent_span_id: str
    flags: int = 1  # sampled by default

    def header(self) -> str:
        return (
            f"v=1;trace={self.trace_id};span={self.span_id};"
            f"parent={self.parent_span_id};flags={self.flags:02x}"
        )

    @property
    def sampled(self) -> bool:
        return bool(self.flags & 0x1)

    @property
    def synthetic(self) -> bool:
        return bool(self.flags & 0x2)


def _hex(rng: random.Random, nbits: int) -> str:
    return f"{rng.getrandbits(nbits):0{nbits // 4}x}"


def new_root(rng: random.Random | None = None, *, sampled: bool = True) -> TraceContext:
    """Create a fresh root trace context (parent=all-zero)."""
    rng = rng or random.Random()
    return TraceContext(
        trace_id=_hex(rng, 128),
        span_id=_hex(rng, 64),
        parent_span_id=ZERO_SPAN,
        flags=0x1 if sampled else 0x0,
    )


def child(
    parent: TraceContext,
    rng: random.Random | None = None,
    *,
    synthetic: bool = False,
) -> TraceContext:
    """Allocate a child span under ``parent``. Trace id is preserved."""
    rng = rng or random.Random()
    flags = parent.flags & 0x1  # inherit sampled bit
    if synthetic:
        flags |= 0x2
    return TraceContext(
        trace_id=parent.trace_id,
        span_id=_hex(rng, 64),
        parent_span_id=parent.span_id,
        flags=flags,
    )


def parse(header: str) -> TraceContext:
    """Parse a wire header. Raises ``TraceError`` on malformed input."""
    if not isinstance(header, str):
        raise TraceError(f"header must be str, got {type(header).__name__}")
    m = _HEADER_RE.match(header)
    if not m:
        raise TraceError(f"malformed trace header: {header!r}")
    trace_id, span_id, parent_id, flags_hex = m.groups()
    if span_id == ZERO_SPAN:
        raise TraceError("span id may not be all-zero")
    if span_id == parent_id:
        raise TraceError("span and parent must differ")
    return TraceContext(trace_id, span_id, parent_id, int(flags_hex, 16))


# ---------------------------------------------------------------------------
# Span recording
# ---------------------------------------------------------------------------


@dataclass
class Span:
    """One recorded call. Mutable until ``finish`` is called."""

    ctx: TraceContext
    name: str
    started_ms: int
    ended_ms: int | None = None
    status: str = "in_progress"  # ok | error | in_progress
    attrs: dict[str, Any] = field(default_factory=dict)

    def finish(self, status: str, ended_ms: int, **attrs: Any) -> None:
        if status not in ("ok", "error"):
            raise ValueError(f"status must be ok|error, got {status!r}")
        self.status = status
        self.ended_ms = ended_ms
        self.attrs.update(attrs)

    def to_record(self) -> dict[str, Any]:
        return {
            "trace_id": self.ctx.trace_id,
            "span_id": self.ctx.span_id,
            "parent_span_id": self.ctx.parent_span_id,
            "name": self.name,
            "status": self.status,
            "started_ms": self.started_ms,
            "ended_ms": self.ended_ms,
            "duration_ms": (
                None if self.ended_ms is None else self.ended_ms - self.started_ms
            ),
            "synthetic": self.ctx.synthetic,
            "attrs": dict(sorted(self.attrs.items())),
        }


class Recorder:
    """In-memory span sink. Production: replace with JSONL append + fsync."""

    def __init__(self) -> None:
        self._spans: list[Span] = []

    def open(self, ctx: TraceContext, name: str, started_ms: int) -> Span:
        span = Span(ctx=ctx, name=name, started_ms=started_ms)
        self._spans.append(span)
        return span

    def records(self) -> list[dict[str, Any]]:
        return [s.to_record() for s in self._spans]

    def tree(self, trace_id: str) -> list[dict[str, Any]]:
        """Return spans for ``trace_id`` ordered as a pre-order tree walk.

        Children appear immediately after their parent. Among siblings,
        order is by ``started_ms`` then ``span_id`` for determinism.
        """
        in_trace = [s.to_record() for s in self._spans if s.ctx.trace_id == trace_id]
        by_parent: dict[str, list[dict[str, Any]]] = {}
        roots: list[dict[str, Any]] = []
        ids = {r["span_id"] for r in in_trace}
        for r in in_trace:
            parent = r["parent_span_id"]
            if parent == ZERO_SPAN or parent not in ids:
                roots.append(r)
            else:
                by_parent.setdefault(parent, []).append(r)
        for kids in by_parent.values():
            kids.sort(key=lambda r: (r["started_ms"], r["span_id"]))
        roots.sort(key=lambda r: (r["started_ms"], r["span_id"]))

        out: list[dict[str, Any]] = []

        def walk(node: dict[str, Any], depth: int) -> None:
            out.append({**node, "depth": depth})
            for c in by_parent.get(node["span_id"], []):
                walk(c, depth + 1)

        for r in roots:
            walk(r, 0)
        return out


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_records(records: Iterable[dict[str, Any]]) -> dict[str, Any]:
    """Validate a batch of span records. Returns a typed report.

    Checks:
      - Exactly one root per trace_id (parent == ZERO_SPAN).
      - Every non-root parent_span_id is present in the same trace.
      - No span_id collisions within a trace.
      - No span is its own parent.
      - Every span has finite duration if status != in_progress.
    """
    records = list(records)
    by_trace: dict[str, list[dict[str, Any]]] = {}
    for r in records:
        by_trace.setdefault(r["trace_id"], []).append(r)

    errors: list[dict[str, Any]] = []
    for trace_id, rs in by_trace.items():
        ids = [r["span_id"] for r in rs]
        if len(set(ids)) != len(ids):
            dupes = sorted({s for s in ids if ids.count(s) > 1})
            errors.append(
                {"code": "duplicate_span_id", "trace_id": trace_id, "span_ids": dupes}
            )
        roots = [r for r in rs if r["parent_span_id"] == ZERO_SPAN]
        if len(roots) != 1:
            errors.append(
                {"code": "wrong_root_count", "trace_id": trace_id, "found": len(roots)}
            )
        id_set = set(ids)
        for r in rs:
            if r["span_id"] == r["parent_span_id"]:
                errors.append(
                    {
                        "code": "self_parent",
                        "trace_id": trace_id,
                        "span_id": r["span_id"],
                    }
                )
            if (
                r["parent_span_id"] != ZERO_SPAN
                and r["parent_span_id"] not in id_set
            ):
                errors.append(
                    {
                        "code": "orphan_span",
                        "trace_id": trace_id,
                        "span_id": r["span_id"],
                        "parent_span_id": r["parent_span_id"],
                    }
                )
            if r["status"] != "in_progress" and r["duration_ms"] is None:
                errors.append(
                    {
                        "code": "missing_duration",
                        "trace_id": trace_id,
                        "span_id": r["span_id"],
                    }
                )
    return {"ok": not errors, "trace_count": len(by_trace), "errors": errors}


def render_tree(tree: list[dict[str, Any]]) -> str:
    """ASCII tree for human eyes. Stable string."""
    lines = []
    for r in tree:
        prefix = "  " * r["depth"] + ("- " if r["depth"] else "* ")
        meta = (
            f"[{r['status']}, {r['duration_ms']}ms"
            f"{', synthetic' if r.get('synthetic') else ''}]"
        )
        lines.append(f"{prefix}{r['name']} {meta} span={r['span_id'][:8]}")
    return "\n".join(lines)


__all__ = [
    "TraceContext",
    "TraceError",
    "Span",
    "Recorder",
    "ZERO_SPAN",
    "new_root",
    "child",
    "parse",
    "validate_records",
    "render_tree",
]
