# jupyter_server_config.py — generated by `jupyter server --generate-config`
c = get_config()
c.ServerApp.token = ''
c.ServerApp.password = ''
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.open_browser = False
